module.exports = {
  sub: "5a9a0497-348d-466b-b740-f1696f3ab377",
  firstName: "John",
  lastName: "Doe",
  fullName: "John Doe",
  permitNumber: 123,
  dateOfBirth: new Date(1994, 8, 30),
  countryOfBirth: "USA",
  email: "john.doe@example.com",
  citizenship: "USA",
  gender: "male",
  address: {
    streetAddress: "123 Main St",
    city: "Anytown",
    state: "CA",
    zipCode: "12345",
    country: "USA",
    isVerifiedAddress: true,
  },
  phoneNumber: "555-1234",
  typeOfRegistration: "E_RESIDENCY",
  willWorkInPhysicalJurisdiction: true,
  firstRegistrationDate: new Date(2022, 1, 1),
  nextSubscriptionPaymentDate: new Date(2023, 1, 1),
  profilePicture: "https://example.com/pic.jpg",
  status: "ACTIVE",
  residencyEndDate: new Date(2024, 1, 1),
  industry: "Energy Industry|Industria Energética",
  regulatoryElection: "Austria|Austria",
  regulatoryElectionSub: "regsub",
};
